mqtt:
    host: 10.0.0.210
    port: 1883
    client: kamstrup
    topic: kamstrup
    qos: 0
    retain: False
    authentication: False
    username: user1
    password: changeit
    tls_enabled: False
    # tls_ca_cert: 
    # tls_cert:
    # tls_key:
    # tls_key_password:
    # tls_insecure: True
    # tls_version: ssl.PROTOCOL_TLSv1_2
serial_device:
    com_port: socket://10.10.3.14:2003
kamstrup:
    parameters:
    - energy
    - volume
    - temp1
    - temp2
    poll_interval: 28
